environment:
  matrix:
    - PYTHON: "C:\\Python35"
      PY_PYTHON: 3.5-32
      PY_PYTHON3: 3.5-32

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # From http://help.appveyor.com/discussions/problems/2569-latest-appveyor-build-platform-update-introduced-a-python-problem#comment_38756340
  - ps: cmd /c ftype Python.File="C:\Windows\py.exe" "%1" %*
  - ftype Python.File

build: off

test_script:
  - hello.py
  - python hello.py
  - hello3.py
  - py -3 hello3.py
