install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # From http://help.appveyor.com/discussions/problems/2569-latest-appveyor-build-platform-update-introduced-a-python-problem#comment_38756340
  - ps: cmd /c ftype Python.File="C:\Windows\py.exe" "%1" %*
  - ftype Python.File

  # Try the fix from https://github.com/camlorn/libaudioverse/commit/2a0aaa1c250e53b1f0b2cb3da30cdfb959548d8a
  - 'c:\python35\python -m pip install -U setuptools sphinx pypandoc'

build: off

test_script:
  - echo Python 3.4 32-bit with an explicit interpreter.
  - C:\Python34\python hello.py
  - echo Python 3.4 32-bit with the launcher.
  - py -3.4-32 hello.py
  - echo Python 3.5 64-bit with an explicit interpreter.
  - C:\Python35-x64\python hello.py
  - echo Python 3.5 64-bit with the launcher.
  - py -3.5 hello.py
  - echo Python 3.5 32-bit with an explicit interpreter.
  - C:\Python35\python hello.py
  - echo Python 3.5 32-bit with the launcher. THIS ONE IS GOING TO FAIL!
  - py -3.5-32 hello.py
