environment:
  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"

build: off

test_script:
  - echo "does this work right off the bat?"
  - hello.py
  - echo "try deleting this reg key"
  - reg delete HKEY_CLASSES_ROOT\.py\OpenWithProgids /f
  - hello.py
  - echo "and compare to executing with the explicit interpreter"
  - python hello.py
