environment:
  matrix:
    - PYTHON: "C:\\Python26"
      PY_PYTHON: 2.6-32

    - PYTHON: "C:\\Python26-x64"
      PY_PYTHON: 2.6

    - PYTHON: "C:\\Python27"
      PY_PYTHON: 2.7-32

    - PYTHON: "C:\\Python27-x64"
      PY_PYTHON: 2.7

    - PYTHON: "C:\\Python33"
      PY_PYTHON: 3.3-32

    - PYTHON: "C:\\Python33-x64"
      PY_PYTHON: 3.3

    - PYTHON: "C:\\Python34"
      PY_PYTHON: 3.4-32

    - PYTHON: "C:\\Python34-x64"
      PY_PYTHON: 3.4

    - PYTHON: "C:\\Python35"
      PY_PYTHON: 3.5-32

    - PYTHON: "C:\\Python35-x64"
      PY_PYTHON: 3.5

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # From http://help.appveyor.com/discussions/problems/2569-latest-appveyor-build-platform-update-introduced-a-python-problem#comment_38756340
  - ps: cmd /c ftype Python.File="C:\Windows\py.exe" "%1" %*
  - ftype Python.File

build: off

test_script:
  - echo "does this work right off the bat?"
  - hello.py
  - echo "try deleting this reg key"
  - reg delete HKEY_CLASSES_ROOT\.py\OpenWithProgids /f
  - hello.py
  - echo "and compare to executing with the explicit interpreter"
  - python hello.py
