os: Visual Studio 2015

build: off

test_script:
  - echo "try deleting this reg key"
  - reg delete HKEY_CLASSES_ROOT\.py\OpenWithProgids
  - hello.py
  - echo "no output above :(  but it works when we explicitly use python below!"
  - python hello.py
